services:
  github-bot:
    build: .
    container_name: github-bot
    env_file:
      - .env
    ports:
      - "9090:8080"
    volumes:
      - ./tokens.sqlite3:/app/tokens.sqlite3
    restart: unless-stopped
