services:
  github-bot:
    build: .
    container_name: github-bot
    env_file:
      - .env
    ports:
      - "9090:8080"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./pages:/app/pages
  db:
    image: postgres:16
    container_name: github-bot-db
    env_file:
      - .env
    ports:
      - "5322:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
